apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-envoy
  name: redis-envoy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-envoy
  template:
    metadata:
      labels:
        app: redis-envoy
    spec:
      containers:
      - image: kaitoii11/redis-envoy:v1@sha256:30b0be8bf60c2821b9f10a6fd416a1e68e3c295439980581cae9856f6c088ce5
        name: redis-envoy
        env:
        - name: SERVICE_NAME
          value: "redis-cluster-leader-headless"
        ports:
          - containerPort: 6379
            name: envoy
          - containerPort: 9901
            name: admin
