apiVersion: v1
kind: Service
metadata:
  name: myapp-envoy
  labels:
    app: redis-envoy
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 6379
    targetPort: envoy
    protocol: TCP
  selector:
    app: redis-envoy
